### ISSUE TITLE
discord appeal

### ISSUE THREAD

**Issue by rekitrelt** [Mauler125/scripts_r5#44]
my discord token got stolen, I changed my password on my phone so no one has access to it except me now but I got banned from R5Reloaded because he posted an invite to his scam server I would like to ask to be unbanned because that wasnt me who did that and I want to download and contribute to the mods

**Comment by r-ex** [comment]
what's your discord tag?

**Comment by rekitrelt** [comment]
Same as my GitHub username, rekitrelt#8331

**Comment by rekitrelt** [comment]
Thank you
